final com 1.2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,25 +10,35 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checks-out your repository
+      - name: Check out code
         uses: actions/checkout@v4
-  
-      - name: Prepare Jenkinsfile Runner
-        run: |
-          curl -O https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip
-          unzip apache-maven-3.9.6-bin.zip
-          rm apache-maven-3.9.6-bin.zip
 
-      - name: Run Jenkinsfile
-        id: run_jenkinsfile
-        run: |
-          docker run --rm -v $(pwd):/workspace -v $(which mvn):/mvn -v /local/jenkinsHome:/jenkinsHome \
-              -e PATH=$PATH:/opt/java/openjdk/jre/bin:/workspace/apache-maven-3.9.6/bin \
-              jenkins/jenkinsfile-runner --runHome /jenkinsHome
+      - name: Create Jenkins Home
+        run: mkdir -p jenkinsHome
 
-      - name: Check Tests Result
-        run: 'if grep -q "Tests run: 4, Failures: 0" /local/jenkinsHome/jobs/job/builds/1/log;  then exit 0; else exit 1; fi'
+      - name: Run Jenkinsfile using jenkinsfile-runner
+        run: |
+          docker run --rm \
+            -v ${{ github.workspace }}:/workspace \
+            -v ${{ github.workspace }}/jenkinsHome:/jenkinsHome \
+            jenkinsci/jenkinsfile-runner \
+            --runHome /jenkinsHome \
+            --file /workspace/Jenkinsfile
+
+      - name: Check test result
+        run: |
+          if grep -q "Tests run: 4, Failures: 0" jenkinsHome/jobs/job/builds/1/log; then
+            echo "Tests passed."
+          else
+            echo "Tests failed."
+            exit 1
+          fi
 
       - name: Check add Contacts
-        run: 'if grep -q "@Test checkAddContacts()" /local/jenkinsHome/jobs/job/builds/1/log;  then exit 0; else exit 1; fi'
-        
+        run: |
+          if grep -q "@Test checkAddContacts()" jenkinsHome/jobs/job/builds/1/log; then
+            echo "checkAddContacts test exists."
+          else
+            echo "checkAddContacts test missing."
+            exit 1
+          fi
